# Default values for jaeger-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hostname: bigbang.dev
istio:
  # Toggle istio integration 
  enabled: false
  jaeger:
    # Toggle vs creation
    enabled: true
    annotations: {}
    labels: {}
    gateways:
      - istio-system/main
    hosts:
      - tracing.{{ .Values.hostname }}


image:
  repository: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-operator
  tag: 1.22.0
  pullPolicy: Always
  imagePullSecrets:
  - private-registry

elasticsearch:
  enabled: false
  username: elastic
  name: logging-ek
  namespace: logging
  # password:

retention:
  enabled: false
  schedule: "0 * * * *"
  days: 5
  image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-es-index-cleaner:1.22.0
  imagePullSecrets:
      - private-registry
jaeger:
  # Specifies whether Jaeger instance should be created
  create: true
  # namespace where Jaeger resource should be created default to .Release.Namespace
  spec: 
    # allInOne for dev purposes
    # production for HA setup
    strategy: allInOne
    annotations: {}
    labels: {}
    allInOne:
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/all-in-one:1.22.0
      options: 
        log-level: info 
      imagePullSecrets:
      - private-registry
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 128Mi
    agent:
      maxReplicas: 5
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-agent:1.22.0
      options: 
        log-level: info
      imagePullSecrets:
      - private-registry
    ingester:
      maxReplicas: 5
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-ingestor:1.22.0
      options: 
        log-level: info
      imagePullSecrets:
      - private-registry
    query:
      maxReplicas: 5
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-query:1.22.0
      options: 
        log-level: info
      imagePullSecrets:
      - private-registry
    collector:
      maxReplicas: 5
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-collector:1.22.0
      options: 
        log-level: info
      imagePullSecrets:
      - private-registry
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 128Mi
    volumeMounts:
      - name: certificates
        mountPath: /es/certificates/
        readOnly: true
    volumes:
      - name: certificates
        secret:
          secretName: elasticsearch-certificates

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false
  clusterRole: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: jaeger-instance

resources: 
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}
