{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-jaeger-kube-dns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {} # all pods in Release namespace
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector: {} # all namespaces
      ports:
        - port: 53
          protocol: UDP
        {{- if .Values.openshift.enabled }}  
        - port: 5353
          protocol: UDP
        {{- end }}
{{- end }}
