{{ if .Values.networkPolicies.enabled }}
# Allow Traffic to authservice
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-jaeger-authservice
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 10003
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
      namespaceSelector:
        matchLabels:
          # https://repo1.dso.mil/platform-one/big-bang/bigbang/-/merge_requests/457
          app.kubernetes.io/name: authservice
{{- end }}