{{ if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-jaeger-kiali
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: kiali   # label match for kiali pods
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kiali
    ports:
      - port: 16686
        protocol: TCP
{{- end }}        