{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
# Allow traffic from the IngressGateway to the query UI
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-jaeger-istio
  namespace:  {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- if eq .Values.jaeger.spec.strategy "allInOne" }}
      app.kubernetes.io/component: all-in-one   
      {{- else }}
      app.kubernetes.io/component: query
      {{- end }}
  ingress:
  - ports:
    - port: 16686
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingressLabels | nindent 10}}
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane
{{- end }}