{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.tempo.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tempo-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.tempo.namespaces }}
        principals: {{ .Values.istio.hardened.tempo.principals }}
{{- end }}
