{{- if .Values.crdUpgrade.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-crd-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    {{ include "jaeger-operator.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "crds/*.yaml").AsConfig | nindent 2 }}
{{- end }}
