{{- if .Values.crdUpgrade.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jaeger-crd-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    {{ include "jaeger-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jaeger-crd-role
subjects:
- kind: ServiceAccount
  name: jaeger-crd-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
