{{- if and .Values.sso.enabled .Values.istio.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kiali-ap
  namespace: {{ default .Release.Namespace .Values.jaeger.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "jaeger-operator.fullname" . }}
    helm.sh/chart: {{ include "jaeger-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/component: jaeger
  {{- if .Values.istio.jaeger.labels }}
{{ toYaml .Values.istio.jaeger.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.jaeger.annotations }}
  annotations:
{{ toYaml .Values.istio.jaeger.annotations | indent 4 }}
  {{- end }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/kiali/sa/kiali-service-account"]
    - source:
        namespaces: ["kiali"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]  
{{- end }}
