{{- if and .Values.monitoring.enabled .Values.istio.enabled .Values.sso.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: monitoring-prometheus-authz-policy
  namespace: {{ default .Release.Namespace .Values.jaeger.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-operator
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/monitoring/sa/monitoring-monitoring-kube-prometheus
    - source:
        namespaces:
        - monitoring
    to:
    - operation:
        methods:
        - GET
        paths:
        - /*
{{- end }}
