{{- if and .Values.istio.enabled .Values.istio.mtls }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: {{ include "jaeger-operator.fullname" . }}
  namespace: {{ .Release.Namespace}}
spec:
  mtls:
    mode: STRICT
{{- end }}
