{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-operator-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.monitoring.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      name: {{ include "jaeger-operator.fullname" . }}
{{- end }}
