{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-operator-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      name: {{ include "jaeger-operator.fullname" . }}
{{- end }}
