{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.prometheus.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: prometheus-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-operator
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.prometheus.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.prometheus.principals | toYaml | nindent 10 }}
{{- end }}
