{{- if and .Values.istio.enabled .Values.istio.hardened.enabled  -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jaeger-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-operator
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["9443"]
{{- end }}
