{{- if and (or .Values.webhooks.mutatingWebhook.create .Values.webhooks.validatingWebhook.create) (.Values.webhooks.service.create) }}
{{- if .Values.webhookCertGen.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jaeger-operator.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "jaeger-operator.labels" . | nindent 4 }}
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.image.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jaeger-operator.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "jaeger-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jaeger-operator.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "jaeger-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jaeger-operator.fullname" . }}-cert
subjects:
  - kind: ServiceAccount
    name: {{ include "jaeger-operator.fullname" . }}-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jaeger-operator.fullname" . }}-cert-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "jaeger-operator.labels" . | nindent 4 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name: {{ include "jaeger-operator.fullname" . }}-cert-create
      labels:
        app: {{ include "jaeger-operator.fullname" . }}-cert-create
    spec:
      containers:
        - name: create
          image: {{ .Values.webhookCertGen.image.repository }}:{{ .Values.webhookCertGen.image.tag }}
          imagePullPolicy: {{ .Values.webhookCertGen.image.pullPolicy }}
          args:
            - create
            - --cert-name=tls.crt
            - --host={{ default "jaeger-operator-webhook-service" .Values.webhooks.service.name }}.{{ .Release.Namespace }}.svc
            - --key-name=tls.key
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ .Values.certs.certificate.secretName }}
          resources:
            {{- toYaml .Values.webhookCertGen.resources | nindent 12 }}
        {{- if .Values.istio.enabled }}
        - name: cleanup-proxy
          image: {{ .Values.webhookCertGen.cleanupProxy.image.repository }}:{{ .Values.webhookCertGen.cleanupProxy.image.tag }}
          securityContext:
            capabilities:
              drop:
                - ALL
          imagePullPolicy: {{ .Values.webhookCertGen.cleanupProxy.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          - |
            until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
            echo \"Sidecar available. Running the command...\";
            x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
          resources:
            {{- toYaml .Values.webhookCertGen.resources | nindent 12 }}
        {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "jaeger-operator.fullname" . }}-cert
      {{- with .Values.webhookCertGen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhookCertGen.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhookCertGen.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webhookCertGen.securityContext }}
      securityContext:
        {{- toYaml .Values.webhookCertGen.securityContext | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
